# Generated by Django 3.0.2 on 2020-02-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaka_app', '0004_auto_20200127_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ingrediente',
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_de_pago', models.CharField(max_length=50)),
                ('fecha', models.TimeField(auto_now_add=True)),
                ('numero_de_transaccion', models.IntegerField()),
                ('productos', models.ManyToManyField(to='amaka_app.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('productos', models.ManyToManyField(to='amaka_app.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrito',
            field=models.ManyToManyField(to='amaka_app.Carrito'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='transacciones',
            field=models.ManyToManyField(to='amaka_app.Transaccion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ingrediente',
            field=models.ManyToManyField(to='amaka_app.Ingrediente'),
        ),
    ]
