# Generated by Django 3.0.2 on 2020-01-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amaka_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamano',
            old_name='t',
            new_name='tamano',
        ),
    ]
