# Generated by Django 3.0.2 on 2020-01-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaka_app', '0002_auto_20200127_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=50)),
                ('rif', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='compania',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='rif',
        ),
    ]
