# Generated by Django 3.0.2 on 2020-01-28 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amaka_app', '0003_auto_20200127_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amaka_app.Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tamano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amaka_app.Tamano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amaka_app.Rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='compania',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amaka_app.Compania'),
            preserve_default=False,
        ),
    ]
